import type { Metadata } from "next";
import Providers from "@/redux/Provider"
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Colennao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
